package model

import (
	"encoding/json"
	"os"
	"path/filepath"

	"example.com/goddlgen/pkg/logger"
)

type ExtType struct {
	NamespacePrefix               string `json:"NamespacePrefix"`
	NamespaceURI                  string `json:"NamespaceURI"`
	EntityIdentifier              string `json:"EntityIdentifier"`
	EntityIdentifierType          string `json:"EntityIdentifierType"`
	EntityIdentifierAutoGenerated string `json:"EntityIdentifierAutoGenerated"`
}

type ValidationType struct {
	MinInclusive string `json:"minInclusive"`
	MaxInclusive string `json:"maxInclusive"`
	TotalDigits  string `json:"totalDigits"`
	MinLength    string `json:"minLength"`
	MaxLength    string `json:"maxLength"`
	MinItems     string `json:"minItems"`
	Pattern      string `json:"pattern"`
	Comment      string `json:"comment"`
	Default      string `json:"default"`
}

type EnumValuesType struct {
	DisplayNames []string `json:"displayNames"`
	Descriptions []string `json:"descriptions"`
	Value        string   `json:"value"`
	Ext          ExtType  `json:"ext"`
}

type FieldType struct {
	Type         string           `json:"type"`
	TypeInner    string           `json:"typeInner"`
	TypeName     string           `json:"typeName"`
	Name         string           `json:"name"`
	Required     bool             `json:"required"`
	DisplayNames []string         `json:"displayNames"`
	Descriptions []string         `json:"descriptions"`
	Ext          ExtType          `json:"ext"`
	Flags        []string         `json:"flags"`
	EnumValues   []EnumValuesType `json:"enumValues"`
	Validation   ValidationType   `json:"validation"`
}

type ClassFile struct {
	ClassType    string           `json:"classType"`
	SuperType    string           `json:"superType"`
	Name         string           `json:"name"`
	DisplayNames []string         `json:"displayNames"`
	Descriptions []string         `json:"descriptions"`
	Ext          ExtType          `json:"ext"`
	Fields       []FieldType      `json:"fields"`
	EnumValues   []EnumValuesType `json:"enumValues"`
}

func ReadAll(startDir string) ([]*ClassFile, error) {
	log := logger.Get()

	result := make([]*ClassFile, 0)

	// Walk through the directory tree
	err := filepath.Walk(startDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			log.Info().Msgf("Error accessing path %s: %v", path, err)
			return err
		}

		// Check if it's a .json file
		if !info.IsDir() && filepath.Ext(path) == ".json" {
			log.Info().Msgf("Found JSON file: %s", path)

			// Read the file
			data, err := os.ReadFile(path)
			if err != nil {
				log.Info().Msgf("Error reading file %s: %v", path, err)
				return nil // Continue walking even if one file fails
			}

			// Parse JSON
			var cf ClassFile
			err = json.Unmarshal(data, &cf)
			if err != nil {
				log.Info().Msgf("Error parsing JSON in %s: %v", path, err)
				return nil // Continue walking
			}

			result = append(result, &cf)
			log.Info().Msgf("Successfully parsed JSON file %s", path)
		}

		return nil
	})

	if err != nil {
		log.Info().Msgf("Error walking directory tree: %v", err)
		os.Exit(1)
	}

	return result, nil
}
